output_folder = "output/"

[fetch_webinar_list]
api_endpoint = "https://api.webinarjam.com/webinarjam/webinars"
output_filename = "webinar_list.json"

[fetch_registrants_by_webinar]
include_year = 2026
exclude_webinars_with_names_containing = [
	# case-insensitive
	"paid",
	"付费"
]
strptime_format = "%A, %d %b %Y, %I:%M %p" # don't change this unless you know what you're doing (for reference: https://docs.python.org/3/library/datetime.html#format-codes)
api_endpoint = "https://api.webinarjam.com/webinarjam/registrants"
output_filename = "registrants_by_webinar.json"

[transform_into_webinars_by_registrant]
output_filename = "webinars_by_registrant.json"

[convert_registrant_data_to_csv]
output_subfolder = "registrants_csv"
first_line = '"First name","Last name","Phone country code","Phone number",Email,IP,Webinar,Session,Event,"Registration date","Attended live","Attended live date","Time to enter live room","Time in live room","Purchased from live room","Revenue from live room","Watched replay","Watched replay date","Time in replay room","Purchased from replay room","Revenue from replay room",Subscribed,"GDPR status","GDPR communications","GDPR date","GDPR IP","Twilio consent date","Twilio marketing consent date","UTM source","UTM medium","UTM campaign","UTM term","UTM content","Total Signups",Country,State/Province'
json_keys = [
	"first_name",
	"last_name",
	"phone_country_code",
	"phone_number",
	"email",
	"ip",
	"webinar",
	"schedule",
	"event",
	"signup_date",
	"attended_live",
	"date_live",
	"entered_live",
	"time_live",
	"purchased_live",
	"revenue_live",
	"attended_replay",
	"date_replay",
	"time_replay",
	"purchased_replay",
	"revenue_replay",
	"subscribed",
	"gdpr_status",
	"gdpr_communications",
	"gdpr_status_date",
	"gdpr_status_ip",
	"twilio_consented_at",
	"twilio_marketing_consented_at",
	"utm_source",
	"utm_medium",
	"utm_campaign",
	"utm_term",
	"utm_content",
	"total_signups",
	# + country and province, but they are dealt with inside the .py file because their values are objects
]

[convert_webinars_by_registrant_to_csv]
output_subfolder = "webinars_by_registrant_csv"

[plots]
output_subfolder = "plots"
